version: "2"
services:
    nginx:
        build: nginx
        ports: 
            - "80:80"
        volumes: 
            - /mnt/hgfs/SharedFolder/code/client/
        links: 
            - uwsgi
        restart: always

    redis:
        build: redis
        ports:
            - "6379:6379"
    uwsgi: 
        build: uwsgi
        volumes: 
            - "/mnt/hgfs/SharedFolder/code/server/"
        links: 
            - redis
            
      